MACRO(LOAD_LIB_GStreamer)                                                   
    SET(LIB_GStreamer_DIR E:/gstreamer/1.0/msvc_x86_64) 
    MESSAGE(STATUS "LIB_GStreamer_DIR: ${LIB_GStreamer_DIR}")                             
    FIND_FILE(GStreamer_INCLUDE_DIR include ${LIB_GStreamer_DIR} NO_DEFAULT_PATH)          
    FIND_FILE(GStreamer_LIBRARY_DIR lib ${LIB_GStreamer_DIR} NO_DEFAULT_PATH)           
                      
    IF(GStreamer_LIBRARY_DIR)
        file(GLOB GStreamer_LIBS ${GStreamer_LIBRARY_DIR}/*.lib)
        MESSAGE(STATUS "GStreamer_LIBRARY_DIR : ${GStreamer_LIBRARY_DIR}")
        # MESSAGE(STATUS "GStreamer_LIBS : ${GStreamer_LIBS}")
    ENDIF()
    
    IF(GStreamer_INCLUDE_DIR)                                                      
        file(GLOB SUBDIRECTORIES ${GStreamer_INCLUDE_DIR}/*)
        set(GStreamer_INCLUDE_DIR "")
        foreach(SUBDIRECTORY ${SUBDIRECTORIES})
            if(IS_DIRECTORY ${SUBDIRECTORY})
                list(APPEND GStreamer_INCLUDE_DIR ${SUBDIRECTORY})
            endif()
        endforeach()
        # MESSAGE(STATUS "GStreamer_INCLUDE_DIR : ${GStreamer_INCLUDE_DIR}")
    ELSE()
        MESSAGE(FATAL_ERROR "GStreamer_LIBS not found!")
    ENDIF()
ENDMACRO()